apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../quip-pathdb.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: heatmaploader
  name: heatmaploader
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: heatmaploader
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../quip-pathdb.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: heatmaploader
    spec:
      containers:
        - env:
            - name: DEBIAN_FRONTEND
              value: noninteractive
            - name: TZ
              value: America/New_York
          image: heatmaploader
          name: quip-hmloader
          resources: {}
          volumeMounts:
            - mountPath: /mnt/data/
              name: heatmaploader-claim0
      restartPolicy: Always
      volumes:
        - name: heatmaploader-claim0
          persistentVolumeClaim:
            claimName: heatmaploader-claim0
status: {}
