apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../quip-pathdb.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: segloader
  name: segloader
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: segloader
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../quip-pathdb.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: segloader
    spec:
      containers:
        - image: segloader
          name: quip-segloader
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: segloader-claim0
      restartPolicy: Always
      volumes:
        - name: segloader-claim0
          persistentVolumeClaim:
            claimName: segloader-claim0
status: {}
